### ISSUE TITLE
Segmentation fault core dumped error

### ISSUE THREAD

**Issue by princeamitlali** [magic282/NeuSum#20]
While running run.sh after running code for some time we got a segmentation error core dumped when model building starts. If any one helps

**Comment by fb-abstract** [comment]
Is this code running successfully?If it works, may I ask some questions?

**Comment by magic282** [comment]
@fb-abstract Please directly post your questions.

**Comment by fb-abstract** [comment]
After running run.sh, the preprocessing part has not read the data. I changed the vocabulary file provided by your SEASS-maser code and read the data. Is this problem related to the vocabulary?If relevant, can you provide a vocabulary of your code?

**Comment by fb-abstract** [comment]
After running run.sh, the preprocessing part has not read the data. I changed the vocabulary file provided by your SEASS-maser code and read the data. Is this problem related to the vocabulary?If relevant, can you provide a vocabulary of your code?

**Comment by magic282** [comment]
From your description, I cannot get any helpful information. Error message is better.

**Comment by fb-abstract** [comment]
2019-07-05 13:46:47,965 [INFO :__main__] My PID is 5072
2019-07-05 13:46:47,965 [INFO :__main__] Namespace(att_vec_size=256, batch_size=64, beam_size=1, brnn_merge='concat', cuda_seed=12345, curriculum=0, dec_dropout=0.0, dec_init='simple', dec_rnn_size=256, dev_input_src='F:\\neusum\\data\\dev\\val.txt.src', dev_ref='F:\\neusum\\data\\dev\\val.txt.tgt', doc_brnn=True, doc_dropout=0.2, doc_enc_size=256, dump_epoch_checkpoint=False, epochs=100, eval_per_batch=1000, extra_shuffle=True, force_max_len=True, freeze_word_vecs_enc=True, gpus=[0], halve_lr_bad_count=100000, input_feed=1, layers=1, learning_rate=0.001, learning_rate_decay=0.5, log_home='F:\\neusum\\data\\models', log_interval=100, max_decode_step=3, max_doc_len=80, max_generator_batches=32, max_grad_norm=5, max_sent_length=100, max_weight_value=15, maxout_pool_size=2, norm_lambda=20, online_process_data=True, optim='adam', param_init=0.1, pre_word_vecs_dec=None, pre_word_vecs_enc='F:\\neusum\\data\\glove\\glove.6B.50d.txt', process_shuffle=False, save_path='F:\\neusum\\data\\models', seed=12345, self_att_size=512, sent_brnn=True, sent_dropout=0.3, sent_enc_size=256, src_vocab='F:\\neusum\\data\\train\\vocab.txt', start_decay_at=8, start_epoch=1, start_eval_batch=1000, tgt_vocab='F:\\neusum\\data\\train\\vocab.txt', train_oracle='F:\\neusum\\data\\train\\train-oracle', train_src='F:\\neusum\\data\\train\\train.txt.src', train_src_rouge='F:\\neusum\\data\\train\\train-reg', train_tgt='F:\\neusum\\data\\train\\train.txt.tgt', use_self_att=False, word_vec_size=50)
2019-07-05 13:46:47,980 [INFO :__main__] My seed is 12345
2019-07-05 13:46:47,996 [INFO :onlinePreprocess] Reading source vocabulary from 'F:\neusum\data\train\vocab.txt'...
2019-07-05 13:46:48,324 [INFO :onlinePreprocess] Loaded 7827 source words
2019-07-05 13:46:48,324 [INFO :onlinePreprocess] Reading target vocabulary from 'F:\neusum\data\train\vocab.txt'...
2019-07-05 13:46:48,605 [INFO :onlinePreprocess] Loaded 7827 target words
2019-07-05 13:46:48,605 [INFO :onlinePreprocess] Preparing training ...
2019-07-05 13:46:48,605 [INFO :onlinePreprocess] Processing F:\neusum\data\train\train.txt.src & F:\neusum\data\train\train.txt.tgt ...
Traceback (most recent call last):
  File "F:/neusum/NeuSum/neusum_pt/train.py", line 376, in <module>
    main()
  File "F:/neusum/NeuSum/neusum_pt/train.py", line 311, in main
    opt.train_src_rouge)
  File "F:\neusum\NeuSum\neusum_pt\onlinePreprocess.py", line 182, in prepare_data_online
    dicts['src'], dicts['tgt'])
  File "F:\neusum\NeuSum\neusum_pt\onlinePreprocess.py", line 124, in makeData
    neusum.Constants.UNK_WORD) for word in srcWords])
  File "F:\neusum\NeuSum\neusum_pt\onlinePreprocess.py", line 124, in <listcomp>
    neusum.Constants.UNK_WORD) for word in srcWords])
  File "F:\neusum\NeuSum\neusum_pt\neusum\Dict.py", line 123, in convertToIdx
    return torch.LongTensor(vec) #.astype('int')
TypeError: an integer is required (got type NoneType)

**Comment by magic282** [comment]
The code failed to convert text tokens to ids. And the vocab size seems to be too small.
Here is my training log as a reference:
```
2018-05-10 03:28:03,877 [INFO :__main__] My seed is 12345
2018-05-10 03:28:07,512 [INFO :__main__] My cuda seed is 12345
2018-05-10 03:28:07,513 [INFO :onlinePreprocess] Reading source vocabulary from '/workspace/data/cnndm/train/vocab.txt.100k'...
2018-05-10 03:28:07,658 [INFO :onlinePreprocess] Loaded 100000 source words
2018-05-10 03:28:07,658 [INFO :onlinePreprocess] Reading target vocabulary from '/workspace/data/cnndm/train/vocab.txt.100k'...
2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Loaded 100000 target words
2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Preparing training ...
2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Processing /workspace/data/cnndm/train/train.txt.src & /workspace/data/cnndm/train/train.txt.tgt ...
```

**Comment by fb-abstract** [comment]
> 代码无法将文本标记转换为ID。词汇量似乎太小了。
> 这是我的培训日志作为参考：
> 
> ```
> 2018-05-10 03:28:03,877 [INFO :__main__] My seed is 12345
> 2018-05-10 03:28:07,512 [INFO :__main__] My cuda seed is 12345
> 2018-05-10 03:28:07,513 [INFO :onlinePreprocess] Reading source vocabulary from '/workspace/data/cnndm/train/vocab.txt.100k'...
> 2018-05-10 03:28:07,658 [INFO :onlinePreprocess] Loaded 100000 source words
> 2018-05-10 03:28:07,658 [INFO :onlinePreprocess] Reading target vocabulary from '/workspace/data/cnndm/train/vocab.txt.100k'...
> 2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Loaded 100000 target words
> 2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Preparing training ...
> 2018-05-10 03:28:07,808 [INFO :onlinePreprocess] Processing /workspace/data/cnndm/train/train.txt.src & /workspace/data/cnndm/train/train.txt.tgt ...
> ```
My question should be a vocabulary question. If you regenerate the vocabulary according to the author's code, this question is also a question, so can you please provide the file of your vocabulary?
